#!/bin/bash

#==============================================================================
# Nome     : atualizar
#            Copyright (c) 2022 Ícaro Vidal Freire 
#------------------------------------------------------------------------------
# Descrição: Função para atualizar repositórios apt e flatpak, além de fazer 
#            uma limpeza básica em pacotes obsoletos ou arquivos de downloads 
#            interrompidos.
# Licença  : The MIT License (MIT)
# Versão   : 0.1.0
#------------------------------------------------------------------------------
# Como usar: Digitar 'atualizar', no terminal  
#==============================================================================

# construindo a função -------------------------------------------------------

atualizar() {
  echo "##### Update dos repositórios =========================================== (1/5)"
  echo
  sudo nala update
  echo 
  echo "##### Upgrade dos repositórios ========================================== (2/5)"
  echo 
  sudo nala upgrade
  echo 
  echo "##### Verificando atualizações no flatpak =============================== (4/5)"
  echo 
  flatpak update 
  echo 
  echo "##### Executando comandos para limpeza ================================== (5/5)"
  echo 
  sudo apt autoclean
  sudo nala autoremove
}

# rodando a função ------------------------------------------------------------

atualizar

# fim do script ---------------------------------------------------------------

exit 

