#!/bin/bash

#===========================================================================
# Nome     : novo-script
#            Copyright (c) 2022 Ícaro Vidal Freire 
#---------------------------------------------------------------------------
# Descrição: Template para futuros scripts em Shell
# Licença  : The MIT License (MIT)
# Versão   : 0.2.0
# Crédito  : Blau Araújo <https://debxp.org>
#---------------------------------------------------------------------------
# Como usar: novo-script <nome-do-script>
#===========================================================================

# variáveis ----------------------------------------------------------------

header="#!/bin/bash

#===========================================================================
# Nome     : $1
#            Copyright (c) $(date '+%Y') Ícaro Vidal Freire 
#---------------------------------------------------------------------------
# Descrição: 
# Licença  : The MIT License (MIT)
# Versão   : 0.1.0
#---------------------------------------------------------------------------
# Como usar: 
#===========================================================================
"

# teste para lembrar o (único) nome de arquivo -----------------------------

[[ $# -ne 1 ]] && "Faltou o (e apenas um único) nome do arquivo desejado!" && exit 1

# teste para saber se o arquivo já existe ----------------------------------

[[ -f $1 ]] && echo "Esse arquivo já existe!" && exit 1

# comandos para criação de uma estrutura de scripts ------------------------

echo "$header" >> $1
chmod +x $1
nvim $1

exit 0
